### PR TITLE
Fix prettier action

### PR DESCRIPTION
**Pull request by michaelkolber**
Prettier is always failing. Let's switch to https://github.com/marketplace/actions/prettier-action in the hopes that it works better.
In addition, make sure subdirectories are checked when labeling.

### CODE REVIEW

**Comment by michaelkolber** [comment]
Hm, Prettier still doesn't work. May just need to roll our own...

**Comment by michaelkolber** [comment]
We shouldn't merge this til it works

**Comment by michaelkolber** [comment]
Gonna wait on https://github.com/actionsx/prettier/issues/22 for this

**Comment by michaelkolber** [comment]
It works!

**Review by ericshermancs — APPROVED** [review]

**Pull request merged**
